import { NextRequest, NextResponse } from 'next/server'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js'
import { z } from 'zod'
import { getVaultClient, VaultClient } from '@/lib/vault-client'
import { buildGraph } from '@/lib/vault-parser'
import { getCachedGraph, computeVaultHash, setCachedGraph } from '@/lib/graph-cache'
import { verifyToken } from '@/lib/mcp-jwt'
import { getStemFromPath } from '@/lib/note-utils'

async function getAuthInfo(req: Request): Promise<{ token: string; clientId: string } | null> {
  const auth = req.headers.get('authorization') ?? ''
  if (!auth.startsWith('Bearer ')) return null
  const rawToken = auth.slice(7)
  try {
    const payload = await verifyToken(rawToken, 'mcp_access')
    return {
      token: rawToken,
      clientId: payload['client_id'] as string,
    }
  } catch {
    return null
  }
}

// Build an in-memory note index from the vault for this request.
// Reuses the graph cache when the vault hash matches — avoids N+1 file fetches.
export async function loadNotes() {
  const client = getVaultClient()
  const tree = await client.getMarkdownTree()
  const vaultHash = computeVaultHash(tree)

  // Reuse cached graph if vault hash matches — avoids N+1 file fetches
  const cached = getCachedGraph(vaultHash)
  if (cached) {
    const noteMap = new Map<string, { path: string; title: string; type: string; tags: string[]; content: string }>()
    for (const note of Object.values(cached.notesByPath)) {
      noteMap.set(note.path, {
        path: note.path,
        title: note.title,
        type: note.type,
        tags: note.tags,
        content: note.content,
      })
    }
    return { noteMap, client }
  }

  // Cache miss — fetch all files and build graph
  const files = await Promise.all(
    tree.map(async f => {
      const { content } = await client.readFile(f.path)
      return [f.path, content] as [string, string]
    })
  )
  const graph = buildGraph(files)
  setCachedGraph(graph, vaultHash)

  // Build a lookup map: path → { title, type, tags, content }
  const noteMap = new Map<string, { path: string; title: string; type: string; tags: string[]; content: string }>()
  for (const [path, content] of files) {
    const node = graph.nodes.find(n => n.path === path)
    if (node) {
      noteMap.set(path, {
        path,
        title: node.title,
        type: node.type,
        tags: node.tags,
        content,
      })
    }
  }
  return { noteMap, client }
}

export function searchNoteMap(
  noteMap: Map<string, { path: string; title: string; type: string; tags: string[]; content: string }>,
  query: string
): { path: string; title: string; type: string }[] {
  const lower = query.toLowerCase()
  return Array.from(noteMap.values())
    .filter(n => n.title.toLowerCase().includes(lower) || n.content.toLowerCase().includes(lower))
    .slice(0, 10)
    .map(n => ({ path: n.path, title: n.title, type: n.type }))
}

export async function getContextText(topic?: string): Promise<string> {
  // fallback: what to show when the file is missing
  // profile/active-projects are intentional user inputs → "(not set up yet)"
  // memory files are auto-generated by Claude Code → "(empty)" when absent
  const claudeFiles = [
    { path: 'Claude/profile.md', header: 'Profile', fallback: '(not set up yet)' },
    { path: 'Claude/active-projects.md', header: 'Active Projects', fallback: '(not set up yet)' },
    { path: 'Claude/memory/user.md', header: 'Memory: User', fallback: '(empty)' },
    { path: 'Claude/memory/feedback.md', header: 'Memory: Feedback', fallback: '(empty)' },
    { path: 'Claude/memory/project.md', header: 'Memory: Projects', fallback: '(empty)' },
    { path: 'Claude/memory/reference.md', header: 'Memory: References', fallback: '(empty)' },
  ]
  let client: VaultClient
  try {
    client = getVaultClient()
  } catch {
    return '(No personal context configured. Create Claude/profile.md in your vault to get started.)'
  }
  const sections: string[] = []
  for (const { path, header, fallback } of claudeFiles) {
    try {
      const { content } = await client.readFile(path)
      sections.push(`## ${header}\n${content.trim() || fallback}`)
    } catch {
      sections.push(`## ${header}\n${fallback}`)
    }
  }
  if (topic) {
    try {
      // TODO: loadNotes() creates a second VaultClient internally; consider passing
      // the existing client to avoid duplicate tree fetches on topic searches.
      const { noteMap } = await loadNotes()
      const results = searchNoteMap(noteMap, topic)
      if (results.length > 0) {
        const lines = results.map(n => `- ${n.path} — ${n.title}`)
        sections.push(`## Related Notes (topic: "${topic}")\n${lines.join('\n')}`)
      }
    } catch { /* search failure is non-fatal */ }
  }
  return sections.join('\n\n')
}

function createMcpServer() {
  const server = new McpServer({
    name: 'superbrain',
    version: '1.0.0',
  })

  // list_notes
  server.tool(
    'list_notes',
    'List vault notes, optionally filtered by folder or tag',
    {
      folder: z.string().optional().describe('Filter by folder prefix, e.g. "people"'),
      tag: z.string().optional().describe('Filter by tag'),
    },
    async ({ folder, tag }) => {
      const { noteMap } = await loadNotes()
      let notes = Array.from(noteMap.values())
      if (folder) notes = notes.filter(n => n.path.startsWith(folder + '/'))
      if (tag) notes = notes.filter(n => n.tags.includes(tag))
      return {
        content: [{
          type: 'text' as const,
          text: JSON.stringify({
            notes: notes.map(n => ({ path: n.path, title: n.title, type: n.type, tags: n.tags })),
          }, null, 2),
        }],
      }
    }
  )

  // search_notes
  server.tool(
    'search_notes',
    'Full-text search across all vault notes by title or content',
    {
      query: z.string().describe('Search query'),
    },
    async ({ query }) => {
      const { noteMap } = await loadNotes()
      const results = searchNoteMap(noteMap, query)
      return {
        content: [{ type: 'text' as const, text: JSON.stringify({ results }, null, 2) }],
      }
    }
  )

  // read_note
  server.tool(
    'read_note',
    'Read a note by its path or title',
    {
      path: z.string().optional().describe('Relative path, e.g. people/Alice Johnson.md'),
      title: z.string().optional().describe('Note title (case-insensitive)'),
    },
    async ({ path, title }) => {
      const { noteMap } = await loadNotes()
      let note = path
        ? noteMap.get(path)
        : Array.from(noteMap.values()).find(n => n.title.toLowerCase() === (title ?? '').toLowerCase())
      if (!note) {
        // fuzzy fallback for title
        const lower = (title ?? path ?? '').toLowerCase()
        note = Array.from(noteMap.values()).find(n => n.title.toLowerCase().includes(lower))
      }
      if (!note) return { content: [{ type: 'text' as const, text: JSON.stringify({ error: 'Note not found' }) }] }
      return {
        content: [{ type: 'text' as const, text: JSON.stringify(note, null, 2) }],
      }
    }
  )

  // write_note
  server.tool(
    'write_note',
    'Create or update a note in the vault. Use kebab-case for the filename (e.g. groups/engineering-team.md), but always set a readable "title" field in the frontmatter with spaces and proper capitalisation (e.g. title: Engineering Team).',
    {
      path: z.string().describe('Relative path using kebab-case, e.g. groups/engineering-team.md'),
      content: z.string().describe('Full markdown content including frontmatter. The frontmatter title must use spaces and Title Case, not the kebab-case filename.'),
    },
    async ({ path, content }) => {
      const { client } = await loadNotes()
      let sha: string | null = null
      try {
        const existing = await client.readFile(path)
        sha = existing.sha
      } catch {
        // new file
      }
      const stem = getStemFromPath(path)
      await client.writeFile(path, content, sha, sha ? `brain: update [[${stem}]]` : `brain: create [[${stem}]]`)
      return {
        content: [{ type: 'text' as const, text: JSON.stringify({ ok: true, path }) }],
      }
    }
  )

  // delete_note
  server.tool(
    'delete_note',
    'Permanently delete a note at the given path. Use with caution — this cannot be undone.',
    {
      path: z.string().describe('Relative path of the note to delete, e.g. notes/old-idea.md'),
    },
    async ({ path }) => {
      const { client } = await loadNotes()
      try {
        const existing = await client.readFile(path)
        const stem = getStemFromPath(path)
        await client.deleteFile(path, existing.sha, `brain: delete [[${stem}]]`)
        return {
          content: [{ type: 'text' as const, text: JSON.stringify({ ok: true, deleted: path }) }],
        }
      } catch (e) {
        const message = e instanceof Error ? e.message : 'Failed to delete note'
        return {
          content: [{ type: 'text' as const, text: JSON.stringify({ error: message }) }],
        }
      }
    }
  )

  // get_related
  server.tool(
    'get_related',
    'Get notes that link to or from a given note',
    {
      path: z.string().describe('Relative path of the note'),
    },
    async ({ path }) => {
      const { noteMap } = await loadNotes()
      const note = noteMap.get(path)
      if (!note) return { content: [{ type: 'text' as const, text: JSON.stringify({ error: 'Note not found' }) }] }

      // Extract [[wikilinks]] from content
      const links = Array.from(note.content.matchAll(/\[\[([^\]]+)\]\]/g)).map(m => m[1])
      const linked = links
        .map(title => Array.from(noteMap.values()).find(n => n.title.toLowerCase() === title.toLowerCase()))
        .filter(Boolean)
        .map(n => ({ path: n!.path, title: n!.title, type: n!.type }))

      // Notes that link back to this note
      const backlinks = Array.from(noteMap.values())
        .filter(n => n.content.includes(`[[${note.title}]]`))
        .map(n => ({ path: n.path, title: n.title, type: n.type }))

      return {
        content: [{ type: 'text' as const, text: JSON.stringify({ linked, backlinks }, null, 2) }],
      }
    }
  )

  // get_context
  server.tool(
    'get_context',
    'Load personal context from the vault (profile, active projects, memory). Optionally search for notes related to a topic.',
    {
      topic: z.string().optional().describe('Optional topic to search for related notes'),
    },
    async ({ topic }) => {
      const text = await getContextText(topic)
      return {
        content: [{ type: 'text' as const, text }],
      }
    }
  )

  return server
}

async function handleMcpRequest(req: NextRequest): Promise<Response> {
  const authInfo = await getAuthInfo(req)
  if (!authInfo) {
    return NextResponse.json({ error: 'Unauthorized' }, {
      status: 401,
      headers: { 'WWW-Authenticate': 'Bearer' },
    })
  }

  const transport = new WebStandardStreamableHTTPServerTransport({ sessionIdGenerator: undefined })
  const server = createMcpServer()
  await server.connect(transport)
  return transport.handleRequest(req, { authInfo: { token: authInfo.token, clientId: authInfo.clientId, scopes: [] } })
}

export async function POST(req: NextRequest) {
  return handleMcpRequest(req)
}

export async function GET(req: NextRequest) {
  return handleMcpRequest(req)
}

export async function DELETE(req: NextRequest) {
  return handleMcpRequest(req)
}
